// <auto-generated />
using AvecStyle_Serveur.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AvecStyle_Serveur.Migrations
{
    [DbContext(typeof(AvecStyle_ServeurContext))]
    partial class AvecStyle_ServeurContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AvecStyle_Serveur.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Shape")
                        .HasColumnType("int");

                    b.Property<string>("ShopURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Article");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 3,
                            Gender = false,
                            ImageURL = "https://qcstreetwear.ca/cdn/shop/files/b509a3888ea40764925e24d68a180c0b_1296x.jpg?v=1700172125",
                            Shape = 3,
                            ShopURL = "https://qcstreetwear.ca/collections/casquettes-et-tuques/products/acrylic-pull-on-moonstruck",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 2,
                            Category = 3,
                            Gender = false,
                            ImageURL = "https://qcstreetwear.ca/cdn/shop/files/unnamedcopie_1296x.jpg?v=1729428533",
                            Shape = 3,
                            ShopURL = "https://qcstreetwear.ca/collections/casquettes-et-tuques/products/beanie-las-vegas-raiders-black",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 3,
                            Category = 3,
                            Gender = false,
                            ImageURL = "https://qcstreetwear.ca/cdn/shop/files/Captured_ecran2023-07-09a12.51.15_1296x.png?v=1689624458",
                            Shape = 3,
                            ShopURL = "https://qcstreetwear.ca/collections/casquettes-et-tuques/products/boston-red-sox-mvp-cap-black-grey",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 4,
                            Category = 3,
                            Gender = false,
                            ImageURL = "https://qcstreetwear.ca/cdn/shop/files/Captured_ecran2023-06-04a09.00.39_1296x.png?v=1686158853",
                            Shape = 3,
                            ShopURL = "https://qcstreetwear.ca/collections/casquettes-et-tuques/products/chicago-bulls-47-mvp-black",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 5,
                            Category = 3,
                            Gender = false,
                            ImageURL = "https://qcstreetwear.ca/cdn/shop/files/TB0A61GB001PrimaryHighRes_1296x.png?v=1730417891",
                            Shape = 3,
                            ShopURL = "https://qcstreetwear.ca/collections/casquettes-et-tuques/products/cross-body-bag-black",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 6,
                            Category = 3,
                            Gender = false,
                            ImageURL = "https://qcstreetwear.ca/cdn/shop/files/Captured_ecran2024-05-09a16.56.11_1296x.png?v=1715288228",
                            Shape = 3,
                            ShopURL = "https://qcstreetwear.ca/collections/casquettes-et-tuques/products/cotton-twill-army-cap-beige",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 7,
                            Category = 3,
                            Gender = false,
                            ImageURL = "https://qcstreetwear.ca/cdn/shop/files/WHC200BDLarge_1296x.png?v=1732455734",
                            Shape = 3,
                            ShopURL = "https://qcstreetwear.ca/collections/casquettes-et-tuques/products/cuffed-knit-beanie-brown",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 8,
                            Category = 3,
                            Gender = false,
                            ImageURL = "https://qcstreetwear.ca/cdn/shop/products/Captured_ecran2020-05-25a14.34.04_1296x.png?v=1590431662",
                            Shape = 3,
                            ShopURL = "https://qcstreetwear.ca/collections/casquettes-et-tuques/products/copy-of-dad-hat-ny-state-of-mind-radiant-brand-navy",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 9,
                            Category = 3,
                            Gender = false,
                            ImageURL = "https://qcstreetwear.ca/cdn/shop/files/unnamed_5_b2127b26-d76e-48f7-bd05-faec6d081271_1296x.jpg?v=1729174716",
                            Shape = 3,
                            ShopURL = "https://qcstreetwear.ca/collections/casquettes-et-tuques/products/mlb-los-angeles-dodgers-black-sand-47-captain",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 10,
                            Category = 3,
                            Gender = false,
                            ImageURL = "https://qcstreetwear.ca/cdn/shop/files/TB0A61HK001PrimaryHighRes_1296x.png?v=1740699932",
                            Shape = 3,
                            ShopURL = "https://qcstreetwear.ca/collections/casquettes-et-tuques/products/timberpack-sling-bag",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 11,
                            Category = 0,
                            Gender = false,
                            ImageURL = "https://qcstreetwear.ca/cdn/shop/files/100075508B0002_1296x.jpg?v=1713555412",
                            Shape = 3,
                            ShopURL = "https://qcstreetwear.ca/collections/hauts-et-t-shirts-pour-hommes/products/above-the-rim-collage-t-shirt-black",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 12,
                            Category = 0,
                            Gender = false,
                            ImageURL = "https://www.streetwearofficial.com/cdn/shop/products/bart-lean-mock-v2.jpg?v=1556866422&width=1200",
                            Shape = 3,
                            ShopURL = "https://www.streetwearofficial.com/products/bart-lean",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 13,
                            Category = 0,
                            Gender = false,
                            ImageURL = "https://www.streetwearofficial.com/cdn/shop/products/00004529763C71D0_X.jpg?v=1560582957&width=800",
                            Shape = 3,
                            ShopURL = "https://www.streetwearofficial.com/products/raheem-toon-tee",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 14,
                            Category = 0,
                            Gender = false,
                            ImageURL = "https://www.streetwearofficial.com/cdn/shop/products/white-blank-new_04878970-3515-4f50-b6a4-73f0a8e28026.jpg?v=1561789729&width=1200",
                            Shape = 3,
                            ShopURL = "https://www.streetwearofficial.com/products/flying-kickz",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 15,
                            Category = 0,
                            Gender = false,
                            ImageURL = "https://www.streetwearofficial.com/cdn/shop/products/Screen_Shot_2018-11-30_at_7.59.48_PM.png?v=1569155394&width=800",
                            Shape = 3,
                            ShopURL = "https://www.streetwearofficial.com/products/hype-kid",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 16,
                            Category = 0,
                            Gender = false,
                            ImageURL = "https://www.streetwearofficial.com/cdn/shop/products/0000332056712060_X.jpg?v=1560582988&width=1000",
                            Shape = 3,
                            ShopURL = "https://www.streetwearofficial.com/products/big-jmpmn-tee",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 17,
                            Category = 0,
                            Gender = false,
                            ImageURL = "https://www.streetwearofficial.com/cdn/shop/products/RK_0011_Screen_Shot_2017-07-06_at_12.24.28_PM_4e956761-a560-4c51-ae0d-38e09e7f983d.jpg?v=1560582953&width=1200",
                            Shape = 3,
                            ShopURL = "https://www.streetwearofficial.com/products/mj-bear-tee",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 18,
                            Category = 0,
                            Gender = false,
                            ImageURL = "https://www.streetwearofficial.com/cdn/shop/products/0000284886248163_X.jpg?v=1568959690&width=1000",
                            Shape = 3,
                            ShopURL = "https://www.streetwearofficial.com/products/mj-mag-tee",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 19,
                            Category = 0,
                            Gender = false,
                            ImageURL = "https://www.streetwearofficial.com/cdn/shop/products/jh-robber-navy.jpg?v=1561792355&width=1600",
                            Shape = 3,
                            ShopURL = "https://www.streetwearofficial.com/products/jh-robber",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 20,
                            Category = 0,
                            Gender = false,
                            ImageURL = "https://www.streetwearofficial.com/cdn/shop/products/110_a8631b08-0e66-4a7e-a4c7-8c6a3c954854.jpg?v=1583438263&width=1200",
                            Shape = 3,
                            ShopURL = "https://www.streetwearofficial.com/products/smooth-criminal",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 21,
                            Category = 1,
                            Gender = false,
                            ImageURL = "https://boutique-streetwear.com/cdn/shop/files/JEAN-VINTAGE-ULTRA_300x.jpg?v=1695643181",
                            Shape = 3,
                            ShopURL = "https://boutique-streetwear.com/collections/pantalons-streetwear/products/jean-vintage-ultra",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 22,
                            Category = 1,
                            Gender = false,
                            ImageURL = "https://boutique-streetwear.com/cdn/shop/files/PANTALON-CARGO-CAMO_300x.jpg?v=1695470160",
                            Shape = 3,
                            ShopURL = "https://boutique-streetwear.com/collections/pantalons-streetwear/products/pantalon-cargo-camo",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 23,
                            Category = 1,
                            Gender = false,
                            ImageURL = "https://boutique-streetwear.com/cdn/shop/files/PANTALON-DE-SURVETEMENT-ANTHRACITE_300x.jpg?v=1695389552",
                            Shape = 3,
                            ShopURL = "https://boutique-streetwear.com/collections/pantalons-streetwear/products/pantalon-de-survetement-anthracite",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 24,
                            Category = 1,
                            Gender = false,
                            ImageURL = "https://boutique-streetwear.com/cdn/shop/files/JEAN-TROUE-HOODED_300x.jpg?v=1692117909",
                            Shape = 3,
                            ShopURL = "https://boutique-streetwear.com/collections/pantalons-streetwear/products/jean-troue-hooded",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 25,
                            Category = 1,
                            Gender = false,
                            ImageURL = "https://boutique-streetwear.com/cdn/shop/products/JEAN-CARGO-STREETWEAR_300x.jpg?v=1673743547",
                            Shape = 3,
                            ShopURL = "https://boutique-streetwear.com/collections/pantalons-streetwear/products/jean-cargo-pockets",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 26,
                            Category = 1,
                            Gender = false,
                            ImageURL = "https://boutique-streetwear.com/cdn/shop/products/SHORT-CARGO-NOIR_300x.png?v=1660680298",
                            Shape = 3,
                            ShopURL = "https://boutique-streetwear.com/collections/pantalons-streetwear/products/short-cargo-en-coton-noir",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 27,
                            Category = 1,
                            Gender = false,
                            ImageURL = "https://boutique-streetwear.com/cdn/shop/products/SHORT-AVEC-CEINTURE_300x.png?v=1660781444",
                            Shape = 3,
                            ShopURL = "https://boutique-streetwear.com/collections/pantalons-streetwear/products/short-en-polyester-avec-ceinture-beige",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 28,
                            Category = 1,
                            Gender = false,
                            ImageURL = "https://boutique-streetwear.com/cdn/shop/products/SHORT-SKATE_300x.png?v=1660752589",
                            Shape = 3,
                            ShopURL = "https://boutique-streetwear.com/collections/pantalons-streetwear/products/short-en-polyester-style-skate-noir",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 29,
                            Category = 1,
                            Gender = false,
                            ImageURL = "https://boutique-streetwear.com/cdn/shop/products/JOGGING-POLYESTER_c75f6678-a7a9-4d17-8ff2-5be70fd379f0_300x.png?v=1660569232",
                            Shape = 3,
                            ShopURL = "https://boutique-streetwear.com/collections/pantalons-streetwear/products/jogging-polyester-vert",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 30,
                            Category = 1,
                            Gender = false,
                            ImageURL = "https://boutique-streetwear.com/cdn/shop/products/PANTALON-CARGO-TECHNIQUE-FLUO_300x.png?v=1660229064",
                            Shape = 3,
                            ShopURL = "https://boutique-streetwear.com/collections/pantalons-streetwear/products/pantalon-cargo-fluo",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 31,
                            Category = 2,
                            Gender = false,
                            ImageURL = "https://nrml.ca/cdn/shop/files/SFTM1.png?crop=center&height=1000&v=1740683845&width=1800",
                            Shape = 3,
                            ShopURL = "https://nrml.ca/collections/all/products/adistar-cushion-song-for-the-mute-releases-march-13",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 32,
                            Category = 2,
                            Gender = false,
                            ImageURL = "https://nrml.ca/cdn/shop/files/YOTS4.jpg?crop=center&height=1000&v=1741892424&width=1800",
                            Shape = 3,
                            ShopURL = "https://nrml.ca/collections/all/products/dunk-low-retro-year-of-the-snake",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 33,
                            Category = 2,
                            Gender = false,
                            ImageURL = "https://nrml.ca/cdn/shop/files/BO2.jpg?crop=center&height=1000&v=1742566656&width=1800",
                            Shape = 3,
                            ShopURL = "https://nrml.ca/collections/all/products/740-triple-black",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 34,
                            Category = 2,
                            Gender = false,
                            ImageURL = "https://nrml.ca/cdn/shop/files/ADV.jpg?crop=center&height=1000&v=1742910732&width=1800",
                            Shape = 3,
                            ShopURL = "https://nrml.ca/collections/all/products/samba-adv-preloved-ink-price-tbd",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 35,
                            Category = 2,
                            Gender = false,
                            ImageURL = "https://nrml.ca/cdn/shop/files/M10000.jpg?crop=center&height=1000&v=1744389766&width=1800",
                            Shape = 3,
                            ShopURL = "https://nrml.ca/collections/all/products/m1000-black-silver-metallic",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 36,
                            Category = 2,
                            Gender = false,
                            ImageURL = "https://nrml.ca/cdn/shop/files/rare_9478dd14-75a4-44f6-84b3-f0a29d1f630c.jpg?crop=center&height=1000&v=1743530232&width=1800",
                            Shape = 3,
                            ShopURL = "https://nrml.ca/collections/all/products/air-jordan-1-retro-high-og-rare-air-april-5",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 37,
                            Category = 2,
                            Gender = false,
                            ImageURL = "https://nrml.ca/cdn/shop/files/ADIFOM.png?crop=center&height=1000&v=1744226432&width=1800",
                            Shape = 3,
                            ShopURL = "https://nrml.ca/collections/all/products/adifom-iiinfinity-mule-crystal-sand",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 38,
                            Category = 2,
                            Gender = false,
                            ImageURL = "https://nrml.ca/cdn/shop/files/OBSI.jpg?crop=center&height=1000&v=1743774042&width=1800",
                            Shape = 3,
                            ShopURL = "https://nrml.ca/collections/all/products/air-jordan-1-retro-low-og-obsidian-release-april-12",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 39,
                            Category = 2,
                            Gender = false,
                            ImageURL = "https://nrml.ca/cdn/shop/files/RCF.jpg?crop=center&height=1000&v=1744736500&width=1800",
                            Shape = 3,
                            ShopURL = "https://nrml.ca/collections/all/products/1906r-black-dark-silver-metallic",
                            Style = "streetwear"
                        },
                        new
                        {
                            Id = 40,
                            Category = 2,
                            Gender = false,
                            ImageURL = "https://nrml.ca/cdn/shop/files/WHTCLOT.jpg?crop=center&height=1000&v=1744743482&width=1800",
                            Shape = 3,
                            ShopURL = "https://nrml.ca/collections/all/products/adidas-gazelle-crepe-x-clot-crew-white-release-apr-19",
                            Style = "streetwear"
                        });
                });

            modelBuilder.Entity("AvecStyle_Serveur.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Image");
                });
#pragma warning restore 612, 618
        }
    }
}
